runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app

#- url: /static
#  static_dir: static
#  application_readable: true

- url: /.*
  static_dir: static
  application_readable: true

libraries:
- name: flask
  version: 0.12



#manual_scaling:
#  instances: 1